name: Build iOS

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create dummy IPA
        run: |
          mkdir -p Payload
          echo "com.example.test" > info.txt
          zip -r test.zip Payload
          mv test.zip Test.ipa
      
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: Test.ipa
